version: '3.7'

services: # This section defines all the services (containers) we want to run
  jaeger: # This is the name we're giving to our service
    image: jaegertracing/all-in-one:latest
    #ports section maps ports from container to computer
    #format is host_port:container_port
    ports:
      - '6831:6831/udp' # Jaeger thrift compact protocol
      - '6832:6832/udp' # Jaeger thrift binary protocol
      - '5778:5778' # Jaeger admin port
      - '16686:16686' # Jaeger UI
      - '4317:4317' # OTLP gRPC
      - '4318:4318' # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
